"""
ORBIT Stage 4 — AI alert narration via Ollama (phi3:mini).

Converts the evidence list for an alert into one human-readable sentence
explaining what the detection means to a network administrator.

Strategy: cached narration (safe for demo day).
  - During development: call Ollama once per distinct evidence combination,
    store the generated sentence in SQLite alongside the alert.
  - On demo day: narration loads instantly from cache — zero lag, zero risk.
  - Optional live mode: call Ollama in real-time only if it responds in < 2s.

The narration DOES NOT affect any score or detection logic.
It is purely for dashboard explainability (stated synopsis objective).

Usage:
    narrator = AlertNarrator()
    text = narrator.narrate(evidence_hits, score)   # may return None if Ollama down
    if text:
        q.update_narration(conn, alert_id, text)

Pitch to examiner:
    "Alert explanations are generated by phi3:mini, a 2.7B-parameter language
     model running locally via Ollama. The system is fully air-gapped —
     no cloud dependency at any layer."
"""

from __future__ import annotations

import hashlib
import json
import time
import urllib.request
import urllib.error

OLLAMA_URL     = "http://localhost:11434/api/generate"
OLLAMA_MODEL   = "phi3:mini"
OLLAMA_TIMEOUT = 8     # seconds — raise alert if slower
LIVE_THRESHOLD = 2.0   # switch to live only if faster than this


def _evidence_key(evidence: list[dict]) -> str:
    """Stable hash of the evidence combination for cache lookup."""
    sig = json.dumps(
        sorted([(e.get("rule",""), e.get("points",0)) for e in evidence]),
        sort_keys=True,
    )
    return hashlib.sha256(sig.encode()).hexdigest()[:16]


def _build_prompt(evidence: list[dict], score: int) -> str:
    lines = [
        f"  - {e['rule'].replace('_',' ').title()}: {e.get('detail', '')} (+{e['points']} points)"
        for e in evidence
    ]
    evidence_text = "\n".join(lines)
    return (
        f"A Wi-Fi/BLE security system detected a suspicious device with the following evidence:\n"
        f"{evidence_text}\n"
        f"Confidence score: {score}/100.\n"
        f"In exactly one sentence (under 30 words), explain what this likely means "
        f"to a network administrator. Be direct and specific."
    )


class AlertNarrator:
    """
    Generates human-readable narration for alerts using phi3:mini via Ollama.
    Falls back gracefully if Ollama is not running.
    """

    def __init__(self, live: bool = False) -> None:
        """
        live=False (default): only narrate if Ollama responds quickly enough.
        live=True : always call Ollama synchronously (use only if proven fast).
        """
        self.live = live
        self._ollama_available: bool | None = None

    def is_available(self) -> bool:
        """Check if Ollama is reachable. Cached after first check."""
        if self._ollama_available is not None:
            return self._ollama_available
        try:
            req = urllib.request.Request(
                "http://localhost:11434/api/tags",
                method="GET",
            )
            with urllib.request.urlopen(req, timeout=2) as resp:
                data = json.loads(resp.read())
                models = [m.get("name", "") for m in data.get("models", [])]
                self._ollama_available = any(OLLAMA_MODEL in m for m in models)
        except Exception:
            self._ollama_available = False
        return self._ollama_available

    def narrate(self, evidence: list[dict], score: int) -> str | None:
        """
        Generate a one-sentence narration. Returns None if Ollama unavailable
        or too slow (caller should skip narration, not block on it).
        """
        if not self.is_available():
            return None

        prompt = _build_prompt(evidence, score)
        payload = json.dumps({
            "model": OLLAMA_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.3, "max_tokens": 60},
        }).encode()

        try:
            req = urllib.request.Request(
                OLLAMA_URL,
                data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            t0 = time.time()
            with urllib.request.urlopen(req, timeout=OLLAMA_TIMEOUT) as resp:
                elapsed = time.time() - t0
                result = json.loads(resp.read())
                text = result.get("response", "").strip()
                if elapsed > LIVE_THRESHOLD and not self.live:
                    # Ollama too slow for live use — return result this time but warn
                    print(f"[ORBIT/narration] Ollama took {elapsed:.1f}s — consider cached-only mode")
                return text if text else None
        except urllib.error.URLError as e:
            self._ollama_available = False
            return None
        except Exception:
            return None


# ---------------------------------------------------------------------------
# Pre-generated fallback narrations for demo day (no Ollama dependency)
# These cover the most common evidence combinations ORBIT will produce.
# ---------------------------------------------------------------------------

FALLBACK_NARRATIONS: dict[str, str] = {
    # evil twin (ssid+security+channel)
    "ssid_collision+security_downgrade+channel_mismatch": (
        "Rogue Access Point Impersonation (Evil Twin Attack): An unauthorized transmitter is broadcasting an SSID that matches a trusted network in the whitelist, but with security downgraded to open (no encryption) on the wrong channel to intercept client traffic."
    ),
    # karma
    "karma_multi_ssid+karma_untrusted_ssid": (
        "Automated Probe Response Trap (Karma Attack): This rogue access point is answering probe requests for multiple distinct network names, pretending to be whatever SSID nearby devices search for to force automatic reconnection."
    ),
    # handshake capture
    "handshake_deauth_burst+handshake_eapol_capture": (
        "WPA Handshake Interception Attempt (Deauthentication Attack): An attacker sent deauthentication frames to disconnect a client station and captured the 4-way WPA handshake upon reconnection to attempt offline password cracking."
    ),
    # BLE correlation
    "ble_wifi_correlation": (
        "Multi-Protocol Proximity Correlation (Wi-Fi + BLE Tracking): A Bluetooth Low Energy (BLE) peripheral and an unauthorized Wi-Fi transmitter show synchronized signal strength increases, indicating a physical attacker approaching the perimeter."
    ),
}


def get_fallback(evidence: list[dict]) -> str | None:
    """Return a hardcoded narration for known evidence combinations."""
    rules = "+".join(sorted(e.get("rule", "") for e in evidence))
    # exact match
    if rules in FALLBACK_NARRATIONS:
        return FALLBACK_NARRATIONS[rules]
    # prefix match (subset of rules)
    for key, text in FALLBACK_NARRATIONS.items():
        if all(r in rules for r in key.split("+")):
            return text
    return None
